### ISSUE TITLE
[DOC] Technologies in Use

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#17]
Section 5.2

"List all the technologies that you plan to use in the project (e.g. programming languages, tools like compiler or IDE, libraries, etc. Give a brief rationale for the use of each technology, i.e. explanations describing why they are appropriate in the context of this project."

**Comment by anitahaurie** [comment]
Can someone in the coding team write this up? You'll have a better idea than anyone in doc.

**Comment by APengue1** [comment]
I can take care of this and consult Chris if I have any questions

**Comment by salaman** [comment]
Some stuff we can include...

- PHP (ease, popularity)
- Laravel framework (rapid development, good documentation, prototyping)
 - [Eloquent ORM](https://laravel.com/docs/5.2/eloquent) (rapid development, built-in query security, abstraction)
- Travis CI (deployments for docs, testing, QA)
- Git (code history, team management, review, issue management)
- optionally Vagrant if people use it (stability, common dev environments)
- Office 365 (document collaboration)
- Not sure if we want to include IDEs/code editors since anyone can use whatever but I highly recommend [PHPStorm](https://www.jetbrains.com/phpstorm/) regardless

**Comment by APengue1** [comment]
Will we still be using Bootstrap?

**Comment by Persepolis1** [comment]
if you are talking about twitter bootstrap, then yes.

**Comment by APengue1** [comment]
More to add:

Bootstrap
Oracle VM VirtualBox
MySQL
Composer (PHP package manager; syncs development packages between devs)
Artisan (included with laravel; runs database migrations)

**Comment by salaman** [comment]
I don't think you should include VirtualBox since it's basically completely invisible and just part of Vagrant. Artisan should be a sub-point in Laravel since it's not a separate tool. Composer should be a sub-point of PHP.

**Comment by APengue1** [comment]
Ok I can maybe add that vagrant provisions a virtual environment using virtual box .. common dev environments including all the stuff we need eg: mysql, php, etc.

Artisan will be part of Lavavel.
Composer will be part of PHP

**Comment by APengue1** [comment]
Should Slack be included?
I think it should as a communications tool.

**Comment by salaman** [comment]
Hmm... I think it would make sense considering I suggested Office 365 be included as well.

**Comment by Persepolis1** [comment]
Hey, I think it would be better to include Slack & Office 365 in "Technical Resources" (my part) .

**Comment by APengue1** [comment]
I agree that the scope of Technologies in Use doesn't seem to include the communications part.
Excerpt from the requirements of tech in use:

"List all the technologies that you plan to use in the project (e.g. programming languages, tools like compiler or IDE, libraries, etc."

**Comment by APengue1** [comment]
This issue can be closed once approved.
